var fs = require("fs");
var path = require("path");

var dir = "C:\\Users\\MOJB-D085-Shashidhar\\.gemini\\antigravity\\scratch\\Crazy-Tax-Tools";

var css = fs.readFileSync(path.join(dir, "static", "css", "style.css"), "utf8");
var js = fs.readFileSync(path.join(dir, "static", "js", "app.js"), "utf8");

var dashboardContent = fs.readFileSync(path.join(dir, "templates", "dashboard.html"), "utf8");
var taxToolsContent = fs.readFileSync(path.join(dir, "templates", "tax_tools.html"), "utf8");
var documentsContent = fs.readFileSync(path.join(dir, "templates", "documents.html"), "utf8");
var reportsContent = fs.readFileSync(path.join(dir, "templates", "reports.html"), "utf8");
var settingsContent = fs.readFileSync(path.join(dir, "templates", "settings.html"), "utf8");

function stripJinja(str) {
  return str
    .replace(/{%\s*extends\s+[^%]+%}/g, "")
    .replace(/{%\s*block\s+[^%]+%}/g, "")
    .replace(/{%\s*endblock\s*%}/g, "")
    .replace(/{{\s*url_for\([^)]+\)\s*}}/g, "#")
    .replace(/{{\s*username[^}]*}}/g, "admin");
}

var fullHtml = [
  '<!DOCTYPE html>',
  '<html lang="en" data-theme="dark">',
  '<head>',
  '  <meta charset="UTF-8">',
  '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
  '  <title>Crazy Tax Tools - Professional Indian Tax & GST Suite</title>',
  '  <meta name="description" content="All-in-one Indian Tax & GST Calculator: Income Tax Old vs New Regime, GST inclusive/exclusive, ITC Reconciler, Section 50 Interest & Late Fee, TDS Master, and GST Tax Invoice Generator.">',
  '  <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>📈</text></svg>">',
  '  <style>',
  css,
  '    .login-gate-overlay {',
  '      min-height: 100vh;',
  '      display: flex;',
  '      align-items: center;',
  '      justify-content: center;',
  '      padding: 1.5rem;',
  '      background: radial-gradient(circle at top right, rgba(37, 99, 235, 0.2), transparent 45%),',
  '                  radial-gradient(circle at bottom left, rgba(16, 185, 129, 0.15), transparent 45%),',
  '                  var(--bg-main);',
  '      position: fixed;',
  '      inset: 0;',
  '      z-index: 9999;',
  '    }',
  '    .login-box {',
  '      width: 100%;',
  '      max-width: 440px;',
  '      background: var(--bg-surface);',
  '      border: 1px solid var(--border-color);',
  '      border-radius: var(--radius-lg);',
  '      padding: 2.5rem;',
  '      box-shadow: var(--shadow-lg);',
  '    }',
  '    .login-gate-alert {',
  '      background: var(--danger-bg);',
  '      border: 1px solid var(--danger);',
  '      color: #fca5a5;',
  '      padding: 0.75rem;',
  '      border-radius: var(--radius-md);',
  '      font-size: 0.85rem;',
  '      margin-bottom: 1.25rem;',
  '      display: none;',
  '      text-align: center;',
  '    }',
  '    .creds-banner {',
  '      background: var(--bg-card);',
  '      border: 1px dashed var(--border-color);',
  '      border-radius: var(--radius-md);',
  '      padding: 0.85rem;',
  '      margin-top: 1.5rem;',
  '      font-size: 0.8rem;',
  '      color: var(--text-muted);',
  '      text-align: center;',
  '      line-height: 1.6;',
  '    }',
  '    .creds-banner code {',
  '      color: var(--primary);',
  '      font-weight: 700;',
  '      background: var(--bg-input);',
  '      padding: 2px 6px;',
  '      border-radius: 4px;',
  '    }',
  '    .pw-input-wrap {',
  '      position: relative;',
  '    }',
  '    .pw-input-wrap .form-input {',
  '      padding-right: 2.5rem;',
  '    }',
  '    .pw-toggle-btn {',
  '      position: absolute;',
  '      right: 0.75rem;',
  '      top: 50%;',
  '      transform: translateY(-50%);',
  '      background: none;',
  '      border: none;',
  '      color: var(--text-muted);',
  '      cursor: pointer;',
  '      font-size: 1rem;',
  '      padding: 0.25rem;',
  '    }',
  '  </style>',
  '</head>',
  '<body>',
  '  <!-- AUTHENTICATION LOGIN GATE -->',
  '  <div id="authLoginGate" class="login-gate-overlay">',
  '    <div class="login-box">',
  '      <div style="text-align: center; margin-bottom: 2rem;">',
  '        <div style="font-size: 3rem; margin-bottom: 0.5rem; filter: drop-shadow(0 4px 6px rgba(0,0,0,0.3));">💼</div>',
  '        <h1 style="font-size: 1.5rem; font-weight: 800; letter-spacing: -0.02em;">Crazy Tax Tools</h1>',
  '        <p style="font-size: 0.85rem; color: var(--text-muted); margin-top: 0.35rem;">Tax Practitioner & Enterprise Portal</p>',
  '      </div>',
  '      <div id="clientLoginError" class="login-gate-alert"></div>',
  '      <form id="clientLoginForm">',
  '        <div class="form-group">',
  '          <label class="form-label" for="loginUsername">Username</label>',
  '          <input type="text" id="loginUsername" class="form-input" placeholder="admin" value="admin" required autofocus>',
  '        </div>',
  '        <div class="form-group">',
  '          <label class="form-label" for="loginPassword">Password</label>',
  '          <div class="pw-input-wrap">',
  '            <input type="password" id="loginPassword" class="form-input" placeholder="Enter password" required>',
  '            <button type="button" class="pw-toggle-btn" id="toggleClientPwBtn" aria-label="Toggle Password Visibility">👁️</button>',
  '          </div>',
  '        </div>',
  '        <div style="display: flex; justify-content: space-between; align-items: center; margin: 1.25rem 0;">',
  '          <label style="display: flex; align-items: center; gap: 0.5rem; font-size: 0.85rem; cursor: pointer;">',
  '            <input type="checkbox" id="loginRemember" checked style="width: 16px; height: 16px;">',
  '            <span>Remember this device</span>',
  '          </label>',
  '        </div>',
  '        <button type="submit" class="btn btn-primary btn-block" style="padding: 0.75rem; font-size: 1rem;">',
  '          🔐 Sign In to Workstation',
  '        </button>',
  '      </form>',
  '      <div class="creds-banner">',
  '        🔑 <strong>Default Login Credentials:</strong><br>',
  '        Username: <code>admin</code> &bull; Password: <code>password123</code>',
  '      </div>',
  '    </div>',
  '  </div>',
  '  <!-- Top Header Navigation -->',
  '  <header class="app-header" style="display: none;">',
  '    <div class="header-container">',
  '      <a href="#dashboard" class="brand-wrapper">',
  '        <span class="brand-icon">💼</span>',
  '        <div class="brand-title">',
  '          Crazy Tax Tools',
  '          <span class="brand-tag">PRO FY 2025-26</span>',
  '        </div>',
  '      </a>',
  '      <nav aria-label="Main Navigation">',
  '        <ul class="nav-links">',
  '          <li><a href="#dashboard" class="nav-link active" data-view="dashboard">📊 Dashboard</a></li>',
  '          <li><a href="#tax-tools" class="nav-link" data-view="tax-tools">🧮 Tax Calculators</a></li>',
  '          <li><a href="#documents" class="nav-link" data-view="documents">🧾 Invoices & Docs</a></li>',
  '          <li><a href="#reports" class="nav-link" data-view="reports">📈 Reports & Logs</a></li>',
  '          <li><a href="#settings" class="nav-link" data-view="settings">⚙️ Settings</a></li>',
  '        </ul>',
  '      </nav>',
  '      <div class="header-actions">',
  '        <span class="fy-badge">AY 2026-27</span>',
  '        <select class="theme-select" id="themeSelect" aria-label="Theme Selection">',
  '          <option value="dark">🌙 Dark Theme</option>',
  '          <option value="light">☀️ Light Theme</option>',
  '          <option value="emerald">🌲 Emerald Theme</option>',
  '        </select>',
  '        <button id="clientLogoutBtn" class="btn btn-sm btn-danger" type="button" title="Sign out of Workstation">🚪 Logout</button>',
  '      </div>',
  '    </div>',
  '  </header>',
  '  <!-- Main Application Body -->',
  '  <main class="main-container" style="display: none;">',
  stripJinja(dashboardContent),
  stripJinja(taxToolsContent),
  stripJinja(documentsContent),
  stripJinja(reportsContent),
  stripJinja(settingsContent),
  '  </main>',
  '  <div class="toast-container" id="toastContainer" aria-live="polite"></div>',
  '  <footer class="app-footer" style="display: none;">',
  '    <div class="footer-container">',
  '      <p>💼 <strong>Crazy Tax Tools</strong> • Designed for Indian Taxation, GST, and Accounting Professionals</p>',
  '      <div class="footer-links">',
  '        <a href="#dashboard" class="footer-link" onclick="location.hash=\'dashboard\'">Dashboard</a>',
  '        <a href="#tax-tools" class="footer-link" onclick="location.hash=\'tax-tools\'">Tax Calculators</a>',
  '        <a href="#documents" class="footer-link" onclick="location.hash=\'documents\'">GST Invoice</a>',
  '      </div>',
  '    </div>',
  '  </footer>',
  '  <script>',
  js,
  '  </script>',
  '</body>',
  '</html>'
].join('\n');

fs.writeFileSync(path.join(dir, "index.html"), fullHtml, "utf8");
console.log("Successfully generated index.html! File length:", fullHtml.length);
